### PR TITLE
tech test

### PR DESCRIPTION
**Pull request by alexfornuto**
Not much that needed to be changed, nice work!

### CODE REVIEW

**Comment by programarivm** [comment]
Thank you @alexfornuto for your proofreading.

**Comment by programarivm** [comment]
Hi @alexfornuto and @pbzona, it's been a couple of weeks since we last discussed about this article -- however it is not been published. I hope everything is ok. May I assist you with anything else? Regards.

**Comment by pbzona** [comment]
Hi @programarivm, we're putting some finishing touches on it and it will be ready soon. There should be one or two final pull requests with some additional (minor changes) within the next week or so, and once those are merged we'll be ready to publish.

**Comment by programarivm** [comment]
Thanks @pbzona. I'm looking forward to seeing this guide published on Linode.

**Pull request merged**
